/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  BaseContract,
  BigNumber,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import { FunctionFragment, Result } from "@ethersproject/abi";
import { Listener, Provider } from "@ethersproject/providers";
import { TypedEventFilter, TypedEvent, TypedListener, OnEvent } from "./common";

export interface ISuperfluidGovernanceInterface extends utils.Interface {
  contractName: "ISuperfluidGovernance";
  functions: {
    "getConfigAsAddress(address,address,bytes32)": FunctionFragment;
    "getConfigAsUint256(address,address,bytes32)": FunctionFragment;
    "registerAgreementClass(address,address)": FunctionFragment;
    "replaceGovernance(address,address)": FunctionFragment;
    "updateContracts(address,address,address[],address)": FunctionFragment;
    "updateSuperTokenLogic(address,address)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "getConfigAsAddress",
    values: [string, string, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getConfigAsUint256",
    values: [string, string, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "registerAgreementClass",
    values: [string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "replaceGovernance",
    values: [string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "updateContracts",
    values: [string, string, string[], string]
  ): string;
  encodeFunctionData(
    functionFragment: "updateSuperTokenLogic",
    values: [string, string]
  ): string;

  decodeFunctionResult(
    functionFragment: "getConfigAsAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getConfigAsUint256",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerAgreementClass",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "replaceGovernance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateContracts",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateSuperTokenLogic",
    data: BytesLike
  ): Result;

  events: {};
}

export interface ISuperfluidGovernance extends BaseContract {
  contractName: "ISuperfluidGovernance";
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: ISuperfluidGovernanceInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    getConfigAsAddress(
      host: string,
      superToken: string,
      key: BytesLike,
      overrides?: CallOverrides
    ): Promise<[string] & { value: string }>;

    getConfigAsUint256(
      host: string,
      superToken: string,
      key: BytesLike,
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { value: BigNumber }>;

    registerAgreementClass(
      host: string,
      agreementClass: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    replaceGovernance(
      host: string,
      newGov: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    updateContracts(
      host: string,
      hostNewLogic: string,
      agreementClassNewLogics: string[],
      superTokenFactoryNewLogic: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    updateSuperTokenLogic(
      host: string,
      token: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  getConfigAsAddress(
    host: string,
    superToken: string,
    key: BytesLike,
    overrides?: CallOverrides
  ): Promise<string>;

  getConfigAsUint256(
    host: string,
    superToken: string,
    key: BytesLike,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  registerAgreementClass(
    host: string,
    agreementClass: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  replaceGovernance(
    host: string,
    newGov: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  updateContracts(
    host: string,
    hostNewLogic: string,
    agreementClassNewLogics: string[],
    superTokenFactoryNewLogic: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  updateSuperTokenLogic(
    host: string,
    token: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    getConfigAsAddress(
      host: string,
      superToken: string,
      key: BytesLike,
      overrides?: CallOverrides
    ): Promise<string>;

    getConfigAsUint256(
      host: string,
      superToken: string,
      key: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    registerAgreementClass(
      host: string,
      agreementClass: string,
      overrides?: CallOverrides
    ): Promise<void>;

    replaceGovernance(
      host: string,
      newGov: string,
      overrides?: CallOverrides
    ): Promise<void>;

    updateContracts(
      host: string,
      hostNewLogic: string,
      agreementClassNewLogics: string[],
      superTokenFactoryNewLogic: string,
      overrides?: CallOverrides
    ): Promise<void>;

    updateSuperTokenLogic(
      host: string,
      token: string,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {};

  estimateGas: {
    getConfigAsAddress(
      host: string,
      superToken: string,
      key: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getConfigAsUint256(
      host: string,
      superToken: string,
      key: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    registerAgreementClass(
      host: string,
      agreementClass: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    replaceGovernance(
      host: string,
      newGov: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    updateContracts(
      host: string,
      hostNewLogic: string,
      agreementClassNewLogics: string[],
      superTokenFactoryNewLogic: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    updateSuperTokenLogic(
      host: string,
      token: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    getConfigAsAddress(
      host: string,
      superToken: string,
      key: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getConfigAsUint256(
      host: string,
      superToken: string,
      key: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    registerAgreementClass(
      host: string,
      agreementClass: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    replaceGovernance(
      host: string,
      newGov: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    updateContracts(
      host: string,
      hostNewLogic: string,
      agreementClassNewLogics: string[],
      superTokenFactoryNewLogic: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    updateSuperTokenLogic(
      host: string,
      token: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
